sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  # login to docker registries (dockerhub + heroku)
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  # install heroku CLI
  - echo "${HEROKU_TOKEN}" | docker login -u "${HEROKU_USERNAME}" --password-stdin registry.heroku.com

before_script:
  - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew clean test
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew bootJar
  - docker build . -t ${DOCKER_USERNAME}/springboot-kotlin-starter
  - docker tag ${DOCKER_USERNAME}/springboot-kotlin-starter registry.heroku.com/${HEROKU_APP_NAME}/web

deploy:
  provider: script
  script:
    docker push ${DOCKER_USERNAME}/springboot-kotlin-starter;
    docker push registry.heroku.com/${HEROKU_APP_NAME}/web;
    heroku container:release web --app ${HEROKU_APP_NAME}
  branch: master
